server:
  port: 9001

spring:
  main:
    banner-mode: off
    allow-bean-definition-overriding: true
  application:
    name: Seekernaut
    description: API for AI Chat Interface
    version: 0.1
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
    async:
      request-timeout: 300000 # 5 minutos em milissegundos
  r2dbc:
    url: r2dbc:postgresql://localhost:9099/Seekernaut
    username: postgresql
    password: postgresql
    pool:
      max-idle-time: PT30S
      max-life-time: PT1H
      max-acquire-time: PT10S
      max-create-connection-time: PT5S
      initial-size: 5
      max-size: 20
  data:
    mongodb:
      uri: "mongodb://localhost:27017/seekernaut_logs" # URI padrão - pode ser sobrescrita nos profiles
  session:
    store-type: jdbc # Configuração padrão para session store
  kafka:
    bootstrap-servers: localhost:9092 # Endereços Kafka padrão
  webflux:
    client:
      connect-timeout: PT5S
      response-timeout: PT10S

seekernaut:
  app:
    jwtSecret: 7YTJDm7ctZQ6SkEEiAU9X0q3yXTBhe5nPhwuOK2APiOZ9cSgm972VU2qcLc2wI0AUYtQy8ESrjqTyKUaJRYdHw==
    jwtExpirationMs: 86400000 # Expiração JWT padrão
    jwtRefreshTokenExpirationDays: 7

logging:
  level:
    root: INFO
    org.springframework.security: DEBUG
    com.seekernaut: INFO # Nível de log padrão para sua aplicação
    org:
      springframework: INFO
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO

ollama:
  base-url: http://localhost:11434/
  title-generation-model: gemma3:1b
  title-generation-prompt: "Levando em consideração o histórico da conversa, gere apenas um título curto e objetivo. Responda APENAS com o título em uma única linha, sem explicações e com menos de 255 caracteres, lembre-se é apenas 1 opção de titulo. Histórico da conversa: "